name: Windows Tailscale RDP
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: 开启远程桌面
        run: |
          Set-ItemProperty 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: 重置远程登录密码
        run: |
          $newPwd = ConvertTo-SecureString "123456Aa!" -AsPlainText -Force
          Set-LocalUser -Name runneradmin -Password $newPwd

      - name: 安装Tailscale
        run: |
          winget install Tailscale.Tailscale --accept-source-agreements --accept-package-agreements
          Start-Sleep 10

      - name: 启动Tailscale并保持机器在线
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up
          while($true) { Start-Sleep 60 }
