name: Windows Tailscale RDP
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: 开启远程桌面
        run: |
          Set-ItemProperty 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: 安装 Tailscale（自动同意协议）
        run: |
          winget install Tailscale.Tailscale --accept-source-agreements --accept-package-agreements
          Start-Sleep 10

      - name: 启动并等待授权
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up
          Start-Sleep 30

      - name: 输出连接IP
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4
